authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: pai
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
nniManagerIp: 10.150.144.59
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Curvefitting
  classArgs:
    start_step: 6
    epoch_num: 20
trial:
  command: python3 mnist.py
  codeDir: /home/v-shhuan/curvefitting_assessor/nni/examples/trials/mnist/.
  gpuNum: 0
  cpuNum: 1
  memoryMB: 32196
  #The docker image to run nni job on pai
  image: fishyds/nni:ydsv0.41
  dataDir: hdfs://10.151.40.179:9000/openmindstudio
  outputDir: hdfs://10.151.40.179:9000/openmindstudio
  virtualCluster: nni
paiConfig:
  #The username to login pai
  userName: openmindstudio
  #The password to login pai
  passWord: Passq1w2e3r4
  #The host of restful server of pai
  host: 10.151.40.179