# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    nodejs: "16"  # specified but actually not used
    # You can also specify other tool versions:
    # rust: "1.55"
    # golang: "1.17"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: dependencies/develop.txt
  - requirements: dependencies/required.txt
  # The issue with smac and swig prevents us from installing required_extra.
  # As a result, the docstring from several tuners including SMAC, PPO cannot be rendered.
  # - requirements: dependencies/required_extra.txt
  - requirements: dependencies/recommended.txt
  # We cannot have `python setup.py install` here,
  # because it's not supported by NNI.
