trigger:
- dev-it

jobs:

- job: 'Ubuntu_16_04'
  pool: 'NNI CI GPU'

  steps:
  - script: python3 -m pip install --upgrade pip setuptools --user
    displayName: 'Install python tools'
  - script: |
      source install.sh
    displayName: 'Install nni toolkit via source code'
  - script: |
      python3 -m pip install sklearn --user
      python3 -m pip install torchvision --user
      python3 -m pip install keras --user
      python3 -m pip install tensorflow==1.9.0 --user
    displayName: 'Install dependencies for integration tests'
  - script: |
      cd test
      source unittest.sh
    displayName: 'Unit test'
  - script: |
      cd test
      PATH=$HOME/.local/bin:$PATH python3 naive_test.py
    displayName: 'Naive test'
  - script: |
      cd test
      PATH=$HOME/.local/bin:$PATH python3 tuner_test.py
    displayName: 'Built-in tuners / assessors tests'
  - script: |
      cd test
      PATH=$HOME/.local/bin:$PATH python3 config_test.py --ts local
    displayName: 'Examples on local machine tests'
