project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /docs/en_US/**/*
    ignore:
      - /docs/zh_CN/**/*
    translation: /docs/%locale_with_underscore%/**/%original_file_name%
  - source: '/**/*.[mM][dD]'
    ignore:
      - '/**/*_%locale_with_underscore%.md'
      - /docs
      - /%locale_with_underscore%
      - /.github
    translation: /%original_path%/%file_name%_%locale_with_underscore%.md
