files:
  - source: '/**/*.[mM][dD]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: '/**/*.[pP][nN][gG]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: '/**/*.[gG][iI][fF]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: '/**/*.[jJ][pP][gG]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: '/**/*.[r/R][sS][tT]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: /docs/*
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: '/**/*.[sS][vV][gG]'
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
