searchSpaceFile: search_space.json
trialCommand: python3 mnist.py  # NOTE: change "python3" to "python" if you are using Windows
trialGpuNumber: 0
trialConcurrency: 4
maxTrialNumber: 20
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Curvefitting
  classArgs:
    epoch_num: 20
    threshold: 0.9
trainingService:
  platform: local
