authorName: default
experimentName: example_mnist_hyperband
maxExecDuration: 1h
maxTrialNum: 10000
trialConcurrency: 10
#choice: local, remote, pai
trainingServicePlatform: paiYarn
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  #choice: Hyperband, BOHB
  #(BOHB should be installed through nnictl)
  builtinAdvisorName: Hyperband
  classArgs:
    #R: the maximum trial budget
    R: 100
    #eta: proportion of discarded trials
    eta: 3
    #choice: maximize, minimize
    optimize_mode: maximize
    #choice: serial, parallelism
    exec_mode: parallelism
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
  cpuNum: 1
  memoryMB: 8196
  #The docker image to run nni job on pai
  image: msranni/nni:latest
paiYarnConfig:
  #The username to login pai
  userName: username
  #The password to login pai
  passWord: password
  #The host of restful server of pai
  host: 10.10.10.10
