searchSpaceFile: search_space.json
trialCommand: python3 mnist.py
trialGpuNumber: 0
trialConcurrency: 2
maxExperimentDuration: 100h
maxTrialNumber: 10000
advisor:
  name: Hyperband
  classArgs:
    R: 100                    # the maximum trial budget (could be the number of mini-batches or epochs) can be
                              # allocated to a trial. Each trial should use trial budget to control how long it runs.
    eta: 3                    # proportion of discarded trials
    optimize_mode: maximize   # maximize or minimize
    exec_mode: parallelism    # serial or parallelism
trainingService:  # For other platforms, check mnist-pytorch example
  platform: local
