authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  #  - ip: 10.150.144.123
  #    username: v-latang
  #    passwd: v-latang
  - ip: 10.214.70.153
    username: FAREAST.v-latang
    sshKeyPath: /mnt/c/Users/v-latang/.ssh/id_rsa
  #    sshKeyPath: /home/v-latang/libs/id_rsa
  - ip: 10.170.68.5
    username: FAREAST.v-latang
    sshKeyPath: /mnt/c/Users/v-latang/.ssh/id_rsa
#    sshKeyPath: /home/v-latang/libs/id_rsa