authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
tuner:
  builtinTunerName: TPE
trial:
  command: python3 mnist.py --batch_num 200
  codeDir: .
  gpuNum: 0
  nasMode: classic_mode
