
jobs:
- job: 'Prerelease_build_upload'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  - script: |
      python3 -m pip install --upgrade pip setuptools --user
      python3 -m pip install twine --user
    displayName: 'Install twine'
  - script: |
      cd deployment/pypi
      make version_ts=true build
    displayName: 'build bdsit_wheel'
  - script: |
      cd deployment/pypi
      twine upload -u $(username) -p $(password) --repository-url https://test.pypi.org/legacy/ dist/*
    displayName: 'upload package to testpypi'

