AUTO_RESUME: True
DATA_DIR: './data/imagenet'
MODEL: 'Childnet_Testing'
RESUME_PATH: './experiments/workspace/ckps/42.pth.tar'
SAVE_PATH: './'
SEED: 42
LOG_INTERVAL: 50
RECOVERY_INTERVAL: 0
WORKERS: 4
NUM_GPU: 2
SAVE_IMAGES: False
AMP: False
OUTPUT: 'None'
EVAL_METRICS: 'prec1'
TTA: 0
LOCAL_RANK: 0

DATASET:
  NUM_CLASSES: 1000
  IMAGE_SIZE: 224 # image patch size
  INTERPOLATION: 'bilinear' # Image resize interpolation type
  BATCH_SIZE: 32 # batch size
  NO_PREFECHTER: False

NET:
  GP: 'avg'
  DROPOUT_RATE: 0.0
  SELECTION: 42

  EMA:
    USE: True
    FORCE_CPU: False # force model ema to be tracked on CPU
    DECAY: 0.9998

OPTIMIZER:
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3