authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: aml
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  image: msranni/nni
amlConfig:
  subscriptionId: ${replace_to_your_subscriptionId}
  resourceGroup: ${replace_to_your_resourceGroup}
  workspaceName: ${replace_to_your_workspaceName}
  computeTarget: ${replace_to_your_computeTarget}
sharedStorage:
  storageType: NFS
  localMountPoint: ${your/local/mount/point}
  remoteMountPoint: ${your/remote/mount/point}
  nfsServer: ${nfs-server-ip}
  exportedDirectory: ${nfs/exported/directory}
  # usermount means you have already mount this storage on localMountPoint
  # nnimount means nni will try to mount this storage on localMountPoint
  # nomount means storage will not mount in local machine, will support partial storages in the future 
  localMounted: nnimount