# FIXME: This pipeline is broken due to resource group location limitation.

trigger: none
pr: none

variables:
  resource_group: nni
  gallery_name: nniImageGallery
  network_security_group: nni-image-builder-nsg
  managed_image_name: nni-linux-image
  image_definition_name: nniLinuxImage
  packer_config: config_linux

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: templates/build-vm-image-template.yml
