# FIXME: This pipeline is broken due to resource group location limitation.

trigger: none
pr: none

variables:
  resource_group: nni-image-builder
  gallery_name: nniImageGalleryV2
  network_security_group: nni-image-builder-nsg
  managed_image_name: nni-windows-image
  image_definition_name: nniWindowsImage
  packer_config: config_windows

jobs:
- job: windows
  pool: nni-it-1es-11
  timeoutInMinutes: 90
  steps:
  - template: templates/build-vm-image-template.yml
