trigger:
- none
resources:
  repositories:
    - repository: azpfilter
      type: github
      name: microsoft/azure-pipeline-filter
      endpoint: github-connection

pool:
  vmImage: ubuntu-latest

variables:
  nni.ci.file.globs: 'a/**/*.txt,a/**/*.js'
  nni.ci.markdown.heading: '#### Test Options'
  nni.ci.markdown.optionIndex: 0
stages:
- stage: Check
  jobs:
  - job: Check
    steps:
    - checkout: azpfilter
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: npm ci
      workingDirectory: 'tools'
      displayName: NPM Install
    - script: node tools/main.mjs
      env:
        NNI_CI_GITHUBPAT: $(nni.ci.githubPAT)
      name: execution
      displayName: Execution
- stage: Main
  dependsOn: Check
  condition: and(succeeded(), ne(dependencies.Check.outputs['Check.execution.skipsubsequent'], 'true'))
  jobs:
  - job: Main
    steps:
    - script: echo end
      displayName: 'Run main test'
