trigger: none

schedules:
- cron: 0 16 * * *
  branches:
    include: [ master ]
  always: true

variables:
  filter.modified.globs: 'pipelines/fast-test.yml,!.github/**,!docs/**,!examples/**'
  filter.prbody.heading: '#### Test Options'
  filter.prbody.optionIndex: 0

stages:
- stage: test
  jobs:
  - job: windows
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 75

    steps:
    - template: templates/install-dependencies.yml
      parameters:
        platform: windows

    - template: templates/install-nni.yml
      parameters:
        user: false

    - script: |
        npm --prefix ts/nni_manager run test
      displayName: TypeScript unit test

    - script: |
        cd test
        python training_service/nnitest/run_tests.py --config training_service/config/pr_tests.yml
      displayName: Simple integration test

  - job: macos
    pool:
      vmImage: macOS-latest

    steps:
    - template: templates/install-dependencies.yml
      parameters:
        platform: macos

    - template: templates/install-nni.yml

    - script: |
        CI=true npm --prefix ts/nni_manager run test --exclude test/core/nnimanager.test.ts
      displayName: TypeScript unit test

    - script: |
        cd test
        python training_service/nnitest/run_tests.py --config training_service/config/pr_tests.yml
      displayName: Simple integration test
