trigger: none
pr: none
# schedules:
# - cron: 0 16 * * *
#   branches:
#     include: [ master ]

jobs:
- job: linux
  pool: nni-it
  timeoutInMinutes: 60

  steps:
  - template: templates/install-dependencies.yml
    parameters:
      platform: ubuntu-latest-gpu
      python_env: venv

  - template: templates/install-nni.yml

  - template: templates/install-customized-tuner.yml

  - script: |
      set -e
      (cd test && python -m pytest ut)
      export PATH=$PATH:$PWD/toolchain/yarn/bin
      export CI=true
      (cd ts/nni_manager && yarn test)
    displayName: SDK unit test

  # TODO: this should be replaced with a dedicated HPO algo test suite

  - script: |
      cd test
      python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
    displayName: Integration test

# TODO: should add a test on platforms other than linux
