trigger: none
pr: none
schedules:
- cron: 0 16 * * *
  branches:
    include: [ master ]

jobs:
- job: local_windows
  pool: NNI CI WINDOWS2
  timeoutInMinutes: 120

  steps:
  - script: |
      python -m pip install -U --upgrade pip setuptools
      python -m pip install -U pytest
    displayName: Install Python tools
  
  - script: |
      python -m pip uninstall nni --yes
      set NNI_RELEASE=999.0
      python setup.py build_ts
      python setup.py bdist_wheel -p win_amd64
      python -m pip install dist/nni-999.0-py3-none-win_amd64.whl
    displayName: Install NNI
  
  - script: |
      python -m pip install -U scikit-learn==0.23.2
      python -m pip install -U keras==2.1.6
      python -m pip install -U torchvision===0.4.1 torch===1.3.1 -f https://download.pytorch.org/whl/torch_stable.html
      python -m pip install -U tensorflow==2.3.1 tensorflow-estimator==2.3.0
      nnictl package install --name=PPOTuner
    displayName: Install extra dependencies
  
  - script: |
      cd examples/tuners/customized_tuner
      python setup.py develop --user
      nnictl package install ./
    displayName: Install example customized tuner
  
  - script: |
      cd test
      python -m pytest ut
      echo "TODO: TypeScript UT"
    displayName: Unit test
    continueOnError: true
  
  - script: |
      cd test
      python nni_test/nnitest/run_tests.py --config config/integration_tests.yml --ts local
    displayName: Integration test
