trigger: none
pr: none
schedules:
- cron: 0 20 * * *
  branches:
    include: [ master ]
  always: true

jobs:
- job: linux
  pool: nni-it-1es-11
  timeoutInMinutes: 60

  steps:
  - template: templates/check-gpu-status.yml

  - template: templates/install-dependencies.yml
    parameters:
      platform: ubuntu-latest-gpu
      python_env: venv

  - template: templates/install-nni.yml

  - template: templates/install-customized-tuner.yml

  - script: |
      cd test
      python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
    displayName: Integration test

  - template: templates/save-crashed-info.yml
