authorName: Unknown
experimentName: enas_macro
trialConcurrency: 4
maxExecDuration: 2400h
maxTrialNum: 20000
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: true
multiPhase: false
tuner:
  builtinTunerName: PPOTuner
  classArgs:
    optimize_mode: maximize
    trials_per_update: 60
    epochs_per_update: 12
    minibatch_size: 10
  #could use the No. 0 gpu for this tuner
  #if want to specify multiple gpus, here is an example of specifying three gpus: 0,1,2
  gpuIndices: 0
trial:
  command: sh ./macro_cifar10.sh
  codeDir: ./
  gpuNum: 1
