authorName: Unknown
experimentName: enas_macro
trialConcurrency: 20
maxExecDuration: 2400h
maxTrialNum: 20000
#choice: local, remote
trainingServicePlatform: pai
#choice: true, false
useAnnotation: true
multiPhase: false
versionCheck: false
nniManagerIp: 0.0.0.0
tuner:
  builtinTunerName: PPOTuner
  classArgs:
    optimize_mode: maximize
    trials_per_update: 60
    epochs_per_update: 20
    minibatch_size: 6
trial:
  command: sh ./macro_cifar10_pai.sh
  codeDir: ./
  gpuNum: 1
  cpuNum: 1
  memoryMB: 8196
  image: msranni/nni:latest
  virtualCluster: nni
  nniManagerNFSMountPath: /home/user/mnt
  containerNFSMountPath: /mnt/data/user
  paiStoragePlugin: team_wise
paiConfig:
  userName: your_account
  token: your_token
  host: 0.0.0.0
