authorName: default
experimentName: simple_weight_sharing
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 3
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  codeDir: ../../tuners/weight_shared_tuner
  classFileName: simple_tuner.py
  className: SimpleTuner
trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 0
machineList:
  - ip: 10.139.139.84
    username: yann
    passwd: Pass_word
  - ip: 10.127.197.109
    username: yann
    passwd: Pass_word
