authorName: default
experimentName: example_pytorch_cifar10
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 1
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: ~/nni/examples/trials/pytorch_cifar10/search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 main.py
  codeDir: ~/nni/examples/trials/pytorch_cifar10
  gpuNum: 1
