_default: !include ./base_pruner.yaml

model_name: resnet56
# pruning setting
config_list: [{
    'sparsity': 0.5,
    'op_types': ['default'],
    'prune_frequency': 10,
    'prune_filters_each_step': 50
}]


