assessors:
- builtinName: Medianstop
  classArgsValidator: nni.algorithms.hpo.medianstop_assessor.MedianstopClassArgsValidator
  className: nni.algorithms.hpo.medianstop_assessor.MedianstopAssessor
  source: nni
- builtinName: Curvefitting
  classArgsValidator: nni.algorithms.hpo.curvefitting_assessor.CurvefittingClassArgsValidator
  className: nni.algorithms.hpo.curvefitting_assessor.CurvefittingAssessor
  source: nni
tuners:
- alias: PPOTuner
  builtinName: PPO
  classArgsValidator: nni.algorithms.hpo.ppo_tuner.PPOClassArgsValidator
  className: nni.algorithms.hpo.ppo_tuner.PPOTuner
  source: nni
- builtinName: SMAC
  classArgsValidator: nni.algorithms.hpo.smac_tuner.SMACClassArgsValidator
  className: nni.algorithms.hpo.smac_tuner.SMACTuner
  source: nni
- builtinName: TPE
  className: nni.algorithms.hpo.tpe_tuner.TpeTuner
  source: nni
- builtinName: TPE_legacy
  classArgs:
    algorithm_name: tpe
  classArgsValidator: nni.algorithms.hpo.hyperopt_tuner.HyperoptClassArgsValidator
  className: nni.algorithms.hpo.hyperopt_tuner.HyperoptTuner
  source: nni
- builtinName: Random
  className: nni.algorithms.hpo.random_tuner.RandomTuner
  classArgsValidator: nni.algorithms.hpo.random_tuner.RandomClassArgsValidator
  source: nni
- builtinName: Anneal
  classArgs:
    algorithm_name: anneal
  classArgsValidator: nni.algorithms.hpo.hyperopt_tuner.HyperoptClassArgsValidator
  className: nni.algorithms.hpo.hyperopt_tuner.HyperoptTuner
  source: nni
- builtinName: Evolution
  classArgsValidator: nni.algorithms.hpo.evolution_tuner.EvolutionClassArgsValidator
  className: nni.algorithms.hpo.evolution_tuner.EvolutionTuner
  source: nni
- acceptClassArgs: false
  alias: BatchTuner
  builtinName: Batch
  className: nni.algorithms.hpo.batch_tuner.BatchTuner
  source: nni
- acceptClassArgs: false
  builtinName: GridSearch
  className: nni.algorithms.hpo.gridsearch_tuner.GridSearchTuner
  source: nni
- builtinName: NetworkMorphism
  classArgsValidator: nni.algorithms.hpo.networkmorphism_tuner.NetworkMorphismClassArgsValidator
  className: nni.algorithms.hpo.networkmorphism_tuner.NetworkMorphismTuner
  source: nni
- alias: MetisTuner
  builtinName: Metis
  classArgsValidator: nni.algorithms.hpo.metis_tuner.MetisClassArgsValidator
  className: nni.algorithms.hpo.metis_tuner.MetisTuner
  source: nni
- alias: GPTuner
  builtinName: GP
  classArgsValidator: nni.algorithms.hpo.gp_tuner.GPClassArgsValidator
  className: nni.algorithms.hpo.gp_tuner.GPTuner
  source: nni
- alias: PBTTuner
  builtinName: PBT
  classArgsValidator: nni.algorithms.hpo.pbt_tuner.PBTClassArgsValidator
  className: nni.algorithms.hpo.pbt_tuner.PBTTuner
  source: nni
- builtinName: RegularizedEvolutionTuner
  classArgsValidator: nni.algorithms.hpo.regularized_evolution_tuner.EvolutionClassArgsValidator
  className: nni.algorithms.hpo.regularized_evolution_tuner.RegularizedEvolutionTuner
  source: nni
- alias: DNGOTuner
  builtinName: DNGO
  classArgsValidator: nni.algorithms.hpo.dngo_tuner.DNGOClassArgsValidator
  className: nni.algorithms.hpo.dngo_tuner.DNGOTuner
  source: nni
- builtinName: Hyperband
  classArgsValidator: nni.algorithms.hpo.hyperband_advisor.HyperbandClassArgsValidator
  className: nni.algorithms.hpo.hyperband_advisor.Hyperband
  isAdvisor: true
  source: nni
- builtinName: BOHB
  classArgsValidator: nni.algorithms.hpo.bohb_advisor.BOHBClassArgsValidator
  className: nni.algorithms.hpo.bohb_advisor.BOHB
  isAdvisor: true
  source: nni
