# The search space of Metis tuner is slightly different from TPE and others.
# See Metis tuner' doc for details: https://nni.readthedocs.io/en/stable/Tuner/MetisTuner.html
searchSpace:
  num_leaves:
    _type: choice
    _value: [31, 28, 24, 20]
  learning_rate:
    _type: choice
    _value: [0.01, 0.05, 0.1, 0.2]
  bagging_freq:
    _type: choice
    _value: [1, 2, 4, 8, 10]

trialCommand: python3 main.py
trialConcurrency: 1
maxTrialNumber: 10
tuner:
  name: MetisTuner
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
