authorName: unknown
experimentName: SPOS Search
trialConcurrency: 2
maxExecDuration: 7d
maxTrialNum: 99999
trainingServicePlatform: local
searchSpacePath: nni_auto_gen_search_space.json
useAnnotation: false
tuner:
  codeDir: .
  classFileName: evolution.py
  className: SPOSEvolution
trial:
  # to fit in a GTX 1080
  command: python tester.py --imagenet-dir /data/ssd1/v-yugzh/imagenet --spos-prep --workers 6
  codeDir: .
  gpuNum: 1
