authorName: unknown
experimentName: SPOS Search
trialConcurrency: 4
maxExecDuration: 7d
maxTrialNum: 99999
trainingServicePlatform: local
searchSpacePath: nni_auto_gen_search_space.json
useAnnotation: false
tuner:
  codeDir: .
  classFileName: tuner.py
  className: EvolutionWithFlops
trial:
  # TODO: change the imagenet dir before release.
  command: python tester.py --imagenet-dir /data/ssd1/v-yugzh/imagenet --spos-prep
  codeDir: .
  gpuNum: 1
