authorName: default
experimentName: GraphNAS
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 2000
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  codeDir: .
  classFileName: graphnas_tuner.py
  className: GraphNASTuner
  classArgs:
    arc_save_path: /tmp/arcs.pkl
trial:
  command: python3 main.py --dataset Citeseer
  codeDir: .
  gpuNum: 0
